name: Spawn
version: '${project.version}'
main: me.rockquiet.spawn.Spawn
api-version: 1.13
author: rockquiet
description: highly configurable spawn plugin
commands:
  spawn:
    description: teleport to spawn
    permission: spawn.use
permissions:
  spawn.use:
    description: teleport to spawn
    default: true
  spawn.bypass.cooldown:
    description: bypass the teleport cooldown
    default: op
  spawn.bypass.delay:
    description: bypass the teleport delay
    default: op
  spawn.bypass.cancel-on-move:
    description: bypass the teleport cancel on move
    default: op
  spawn.bypass.void-teleport:
    description: bypass the void teleport
    default: op
  spawn.bypass.respawn-teleport:
    description: bypass the respawn teleport
    default: op
  spawn.bypass.join-teleport:
    description: bypass the join teleport
    default: op
  spawn.bypass.world-list:
    description: bypass the world-list
    default: op
  spawn.others:
    description: teleport another player to spawn
    default: op
  spawn.set:
    description: set spawn at current location
    default: op
  spawn.reload:
    description: reload all files
    default: op
  spawn.bypass.*:
    default: false
    description: grants all bypass permissions
    children:
      spawn.bypass.cooldown: true
      spawn.bypass.delay: true
      spawn.bypass.cancel-on-move: true
      spawn.bypass.void-teleport: true
      spawn.bypass.respawn-teleport: true
      spawn.bypass.join-teleport: true
      spawn.bypass.world-list: true
  spawn.*:
    default: false
    description: grants all spawn permissions
    children:
      spawn.use: true
      spawn.bypass.*: true
      spawn.others: true
      spawn.set: true
      spawn.reload: true
